"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class servo_check(object):
    __slots__ = ["ref_angle"]

    __typenames__ = ["float"]

    __dimensions__ = [[12]]

    def __init__(self):
        self.ref_angle = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(servo_check._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12f', *self.ref_angle[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != servo_check._get_packed_fingerprint():
            raise ValueError("Decode error")
        return servo_check._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = servo_check()
        self.ref_angle = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if servo_check in parents: return 0
        tmphash = (0xd9d4dd006ca2364a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if servo_check._packed_fingerprint is None:
            servo_check._packed_fingerprint = struct.pack(">Q", servo_check._get_hash_recursive([]))
        return servo_check._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

