"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class velocity(object):
    __slots__ = ["vx", "vy", "wz"]

    __typenames__ = ["float", "float", "float"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.vx = 0.0
        self.vy = 0.0
        self.wz = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(velocity._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.vx, self.vy, self.wz))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != velocity._get_packed_fingerprint():
            raise ValueError("Decode error")
        return velocity._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = velocity()
        self.vx, self.vy, self.wz = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if velocity in parents: return 0
        tmphash = (0x1d2425098c65b07a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if velocity._packed_fingerprint is None:
            velocity._packed_fingerprint = struct.pack(">Q", velocity._get_hash_recursive([]))
        return velocity._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

