"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class body_velocity(object):
    __slots__ = ["vx", "vy", "vz", "wx", "wy", "wz"]

    __typenames__ = ["float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.vx = 0.0
        self.vy = 0.0
        self.vz = 0.0
        self.wx = 0.0
        self.wy = 0.0
        self.wz = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(body_velocity._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ffffff", self.vx, self.vy, self.vz, self.wx, self.wy, self.wz))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != body_velocity._get_packed_fingerprint():
            raise ValueError("Decode error")
        return body_velocity._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = body_velocity()
        self.vx, self.vy, self.vz, self.wx, self.wy, self.wz = struct.unpack(">ffffff", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if body_velocity in parents: return 0
        tmphash = (0x7981d02d4a896302) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if body_velocity._packed_fingerprint is None:
            body_velocity._packed_fingerprint = struct.pack(">Q", body_velocity._get_hash_recursive([]))
        return body_velocity._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

