"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ef_point(object):
    __slots__ = ["x", "y", "z"]

    __typenames__ = ["float", "float", "float"]

    __dimensions__ = [[4], [4], [4]]

    def __init__(self):
        self.x = [ 0.0 for dim0 in range(4) ]
        self.y = [ 0.0 for dim0 in range(4) ]
        self.z = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(ef_point._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.x[:4]))
        buf.write(struct.pack('>4f', *self.y[:4]))
        buf.write(struct.pack('>4f', *self.z[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ef_point._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ef_point._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ef_point()
        self.x = struct.unpack('>4f', buf.read(16))
        self.y = struct.unpack('>4f', buf.read(16))
        self.z = struct.unpack('>4f', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ef_point in parents: return 0
        tmphash = (0xf57106dccbb9ebdd) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ef_point._packed_fingerprint is None:
            ef_point._packed_fingerprint = struct.pack(">Q", ef_point._get_hash_recursive([]))
        return ef_point._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

